server:
  port: 8090

spring:
  # H2 Database set
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB (In-Memory Mode)
    #url: 'jdbc:h2:~/test'    # H2 DB (Embedded Mode)
    username: root        # H2 DB ID
    password: root        # H2 DB PW

  # H2 Console set
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA set
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # DB (none, create, create-drop, update, validate)
      ddl-auto: create
    show_sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
